### ISSUE TITLE
Get error 'No module named flask_migrate'

### ISSUE THREAD

**Issue by shershen08** [masterzh01/sofia#2]
When calling ```>>python monitor.py```
I get:
```
Traceback (most recent call last):
  File "monitor.py", line 8, in <module>
    from manage import db, Memory
  File "/Users/mkuznetcov/Downloads/sofia-master/manage.py", line 10, in <module>
    from flask_migrate import Migrate
ImportError: No module named flask_migrate
```

**Comment by masterzh01** [comment]
@shershen08 
```
$ pip instatll Flask-Migrate
```

**Comment by shershen08** [comment]
Yes I've tried that  earlier, it gives
 **pip install Flask-Migrate**

```
Requirement already satisfied: Flask-Migrate in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages
Requirement already satisfied: Flask-Script>=0.6 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from Flask-Migrate)
Requirement already satisfied: Flask>=0.9 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from Flask-Migrate)
...
```

**Comment by masterzh01** [comment]
It supports python-2.7 only. The higher version has not been tested.

**Comment by shershen08** [comment]
ok, i'll try with python 2 in virtualenv then
